import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from app.core.config import settings
from typing import List


async def send_email(
    subject: str,
    body: str,
    recipients: List[str],
    cc: List[str] = None
) -> bool:
    """
    Send email using SMTP
    
    Args:
        subject: Email subject
        body: Email body (HTML or plain text)
        recipients: List of recipient email addresses
        cc: List of CC email addresses
        
    Returns:
        True if successful, False otherwise
    """
    if not settings.SMTP_USERNAME or not settings.SMTP_PASSWORD:
        raise Exception("SMTP credentials not configured")
    
    try:
        # Create message
        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From'] = f"{settings.SMTP_FROM_NAME} <{settings.SMTP_FROM_EMAIL}>"
        msg['To'] = ', '.join(recipients)
        
        if cc:
            msg['Cc'] = ', '.join(cc)
        
        # Attach body
        msg.attach(MIMEText(body, 'html'))
        
        # Send email
        with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as server:
            server.starttls()
            server.login(settings.SMTP_USERNAME, settings.SMTP_PASSWORD)
            
            all_recipients = recipients + (cc if cc else [])
            server.sendmail(settings.SMTP_FROM_EMAIL, all_recipients, msg.as_string())
        
        return True
        
    except Exception as e:
        print(f"Failed to send email: {e}")
        return False


def generate_meeting_summary_email(meeting_title: str, summary: str, decisions: List[str], action_items: List[dict]) -> str:
    """Generate HTML email template for meeting summary"""
    
    decisions_html = "".join([f"<li>{d}</li>" for d in decisions])
    actions_html = "".join([
        f"<li><strong>{a.get('description')}</strong> - Assigned to: {a.get('assigned_to', 'Unassigned')} - Due: {a.get('due_date', 'No date')}</li>"
        for a in action_items
    ])
    
    html = f"""
    <html>
      <head>
        <style>
          body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
          h1 {{ color: #4F46E5; }}
          h2 {{ color: #6366F1; margin-top: 20px; }}
          ul {{ padding-left: 20px; }}
          li {{ margin-bottom: 8px; }}
        </style>
      </head>
      <body>
        <h1>Meeting Summary: {meeting_title}</h1>
        
        <h2>Summary</h2>
        <p>{summary}</p>
        
        <h2>Decisions Made</h2>
        <ul>
          {decisions_html if decisions_html else '<li>No decisions recorded</li>'}
        </ul>
        
        <h2>Action Items</h2>
        <ul>
          {actions_html if actions_html else '<li>No action items</li>'}
        </ul>
        
        <hr style="margin-top: 30px; border: none; border-top: 1px solid #ddd;">
        <p style="font-size: 12px; color: #666;">
          This email was generated by Meeting Intelligence Platform
        </p>
      </body>
    </html>
    """
    
    return html
